package com.example.kusinakode.domain.pantry

/**
 * Local ingredient book. The server stores ids and quantities only —
 * names and lore never leave the device. Ids match REST/lib/ingredients.php.
 */
object IngredientCatalog {

    val all: List<Ingredient> = listOf(
        ing("ing_all_purpose_flour", "All-purpose Flour", "Harina", "Grain/Baking", Rarity.COMMON,
            "All-purpose Flour (Harina) is a grain/baking on a Filipino table."),
        ing("ing_annatto_oil", "Annatto Oil", "Atsuete Oil", "Spice/Condiment", Rarity.COMMON,
            "Annatto Oil (Atsuete Oil) is a spice/condiment on a Filipino table."),
        ing("ing_annatto_powder_seeds", "Annatto Powder/Seeds", "Atsuete", "Spice", Rarity.COMMON,
            "Annatto Powder/Seeds (Atsuete) is a spice on a Filipino table."),
        ing("ing_bagoong_fermented_fish_paste", "Bagoong (Fermented Fish Paste)", "Bagoong Isda", "Condiment", Rarity.COMMON,
            "Bagoong (Fermented Fish Paste) (Bagoong Isda) is a condiment on a Filipino table."),
        ing("ing_bamboo_skewers", "Bamboo Skewers", "Tuhog na Kawayan", "Tool/Utensil", Rarity.COMMON,
            "Bamboo Skewers (Tuhog na Kawayan) is a tool/utensil on a Filipino table."),
        ing("ing_bamboo_tube", "Bamboo Tube", "Bagakay/Kawayan", "Tool/Cookware", Rarity.RARE,
            "Bamboo Tube (Bagakay/Kawayan) is a tool/cookware on a Filipino table."),
        ing("ing_banana_blossoms_dried", "Banana Blossoms (Dried)", "Puso ng Saging (Tuyo)", "Vegetable", Rarity.COMMON,
            "Banana Blossoms (Dried) (Puso ng Saging (Tuyo)) is a vegetable on a Filipino table."),
        ing("ing_banana_leaves", "Banana Leaves", "Dahon ng Saging", "Wrapper/Tool", Rarity.COMMON,
            "Banana Leaves (Dahon ng Saging) is a wrapper/tool on a Filipino table."),
        ing("ing_batwan_sour_fruit", "Batwan (Sour Fruit)", "Batuan", "Fruit", Rarity.RARE,
            "Batwan (Sour Fruit) (Batuan) is a fruit on a Filipino table."),
        ing("ing_bay_leaves", "Bay Leaves", "Laurel", "Spice/Herb", Rarity.COMMON,
            "Bay Leaves (Laurel) is a spice/herb on a Filipino table."),
        ing("ing_beef", "Beef", "Karne ng Baka", "Protein", Rarity.COMMON,
            "Beef (Karne ng Baka) is a protein on a Filipino table."),
        ing("ing_beef_broth_stock", "Beef Broth/Stock", "Sabaw ng Baka", "Liquid/Base", Rarity.COMMON,
            "Beef Broth/Stock (Sabaw ng Baka) is a liquid/base on a Filipino table."),
        ing("ing_beef_cube_powder", "Beef Cube/Powder", "Beef Cube", "Seasoning", Rarity.COMMON,
            "Beef Cube/Powder (Beef Cube) is a seasoning on a Filipino table."),
        ing("ing_bell_peppers_red_green", "Bell Peppers (Red/Green)", "Sili Pula/Berde", "Vegetable", Rarity.COMMON,
            "Bell Peppers (Red/Green) (Sili Pula/Berde) is a vegetable on a Filipino table."),
        ing("ing_bitter_melon", "Bitter Melon", "Ampalaya", "Vegetable", Rarity.COMMON,
            "Bitter Melon (Ampalaya) is a vegetable on a Filipino table."),
        ing("ing_black_beans_salted_tausi", "Black Beans, Salted (Tausi)", "Tausi", "Condiment", Rarity.COMMON,
            "Black Beans, Salted (Tausi) (Tausi) is a condiment on a Filipino table."),
        ing("ing_bok_choy_shanghai", "Bok Choy / Shanghai", "Petsay Shanghai", "Vegetable", Rarity.COMMON,
            "Bok Choy / Shanghai (Petsay Shanghai) is a vegetable on a Filipino table."),
        ing("ing_bread_banana_or_other_leaves", "Bread (Banana or Other Leaves)", "Puto/Bibingka Wrapper Leaf", "Wrapper", Rarity.COMMON,
            "Bread (Banana or Other Leaves) (Puto/Bibingka Wrapper Leaf) is a wrapper on a Filipino table."),
        ing("ing_butter", "Butter", "Mantikilya", "Dairy", Rarity.COMMON,
            "Butter (Mantikilya) is a dairy on a Filipino table."),
        ing("ing_cabbage", "Cabbage", "Repolyo", "Vegetable", Rarity.COMMON,
            "Cabbage (Repolyo) is a vegetable on a Filipino table."),
        ing("ing_calamansi_juice_fruit", "Calamansi (Juice/Fruit)", "Calamansi", "Fruit", Rarity.COMMON,
            "Calamansi (Juice/Fruit) (Calamansi) is a fruit on a Filipino table."),
        ing("ing_carrots", "Carrots", "Karot", "Vegetable", Rarity.COMMON,
            "Carrots (Karot) is a vegetable on a Filipino table."),
        ing("ing_catfish", "Catfish", "Hito", "Protein", Rarity.COMMON,
            "Catfish (Hito) is a protein on a Filipino table."),
        ing("ing_celery", "Celery", "Kintsay", "Vegetable/Herb", Rarity.COMMON,
            "Celery (Kintsay) is a vegetable/herb on a Filipino table."),
        ing("ing_chayote", "Chayote", "Sayote", "Vegetable", Rarity.COMMON,
            "Chayote (Sayote) is a vegetable on a Filipino table."),
        ing("ing_cheddar_cheese", "Cheddar Cheese", "Keso", "Dairy", Rarity.COMMON,
            "Cheddar Cheese (Keso) is a dairy on a Filipino table."),
        ing("ing_chicharon", "Chicharon", "Chicharon", "Snack/Protein", Rarity.COMMON,
            "Chicharon (Chicharon) is a snack/protein on a Filipino table."),
        ing("ing_chicken", "Chicken", "Manok", "Protein", Rarity.COMMON,
            "Chicken (Manok) is a protein on a Filipino table."),
        ing("ing_chicken_broth_stock", "Chicken Broth/Stock", "Sabaw ng Manok", "Liquid/Base", Rarity.COMMON,
            "Chicken Broth/Stock (Sabaw ng Manok) is a liquid/base on a Filipino table."),
        ing("ing_chicken_liver", "Chicken Liver", "Atay ng Manok", "Protein/Offal", Rarity.COMMON,
            "Chicken Liver (Atay ng Manok) is a protein/offal on a Filipino table."),
        ing("ing_chili_flakes", "Chili Flakes", "Giniling na Sili", "Spice", Rarity.COMMON,
            "Chili Flakes (Giniling na Sili) is a spice on a Filipino table."),
        ing("ing_chili_paste_sambal", "Chili Paste / Sambal", "Sili Paste", "Condiment", Rarity.UNCOMMON,
            "Chili Paste / Sambal (Sili Paste) is a condiment on a Filipino table."),
        ing("ing_chili_pepper_birds_eye", "Chili Pepper (Bird's Eye)", "Siling Labuyo", "Spice/Vegetable", Rarity.COMMON,
            "Chili Pepper (Bird's Eye) (Siling Labuyo) is a spice/vegetable on a Filipino table."),
        ing("ing_chili_pepper_long_green_siling", "Chili Pepper (Long Green / Siling)", "Siling Pansigang", "Vegetable", Rarity.COMMON,
            "Chili Pepper (Long Green / Siling) (Siling Pansigang) is a vegetable on a Filipino table."),
        ing("ing_chili_pepper_red_hot", "Chili Pepper (Red/Hot)", "Siling Pula", "Spice/Vegetable", Rarity.COMMON,
            "Chili Pepper (Red/Hot) (Siling Pula) is a spice/vegetable on a Filipino table."),
        ing("ing_cinnamon", "Cinnamon", "Kanela", "Spice", Rarity.COMMON,
            "Cinnamon (Kanela) is a spice on a Filipino table."),
        ing("ing_coconut_cream", "Coconut Cream", "Kakang Gata", "Dairy Alternative", Rarity.COMMON,
            "Coconut Cream (Kakang Gata) is a dairy alternative on a Filipino table."),
        ing("ing_coconut_meat", "Coconut Meat", "Buko/Laman ng Niyog", "Fruit", Rarity.COMMON,
            "Coconut Meat (Buko/Laman ng Niyog) is a fruit on a Filipino table."),
        ing("ing_coconut_milk", "Coconut Milk", "Gata", "Dairy Alternative", Rarity.COMMON,
            "Coconut Milk (Gata) is a dairy alternative on a Filipino table."),
        ing("ing_coconut_water_young", "Coconut Water (Young)", "Buko Juice", "Beverage/Liquid", Rarity.COMMON,
            "Coconut Water (Young) (Buko Juice) is a beverage/liquid on a Filipino table."),
        ing("ing_cooking_oil", "Cooking Oil", "Mantika", "Fat/Oil", Rarity.COMMON,
            "Cooking Oil (Mantika) is a fat/oil on a Filipino table."),
        ing("ing_cornstarch", "Cornstarch", "Gawgaw", "Thickener", Rarity.COMMON,
            "Cornstarch (Gawgaw) is a thickener on a Filipino table."),
        ing("ing_cucumber", "Cucumber", "Pipino", "Vegetable", Rarity.COMMON,
            "Cucumber (Pipino) is a vegetable on a Filipino table."),
        ing("ing_curry_powder", "Curry Powder", "Curry Powder", "Spice Blend", Rarity.COMMON,
            "Curry Powder (Curry Powder) is a spice blend on a Filipino table."),
        ing("ing_daikon_radish", "Daikon Radish", "Labanos", "Vegetable", Rarity.COMMON,
            "Daikon Radish (Labanos) is a vegetable on a Filipino table."),
        ing("ing_dried_fish_shrimp", "Dried Fish/Shrimp", "Tuyo/Dilis", "Protein", Rarity.COMMON,
            "Dried Fish/Shrimp (Tuyo/Dilis) is a protein on a Filipino table."),
        ing("ing_dried_shrimp_hibe", "Dried Shrimp (Hibe)", "Hibe", "Protein/Seasoning", Rarity.COMMON,
            "Dried Shrimp (Hibe) (Hibe) is a protein/seasoning on a Filipino table."),
        ing("ing_eel", "Eel", "Palos", "Protein", Rarity.UNCOMMON,
            "Eel (Palos) is a protein on a Filipino table."),
        ing("ing_egg_whole", "Egg (Whole)", "Itlog", "Protein", Rarity.COMMON,
            "Egg (Whole) (Itlog) is a protein on a Filipino table."),
        ing("ing_eggplant_chinese_indian", "Eggplant (Chinese/Indian)", "Talong", "Vegetable", Rarity.COMMON,
            "Eggplant (Chinese/Indian) (Talong) is a vegetable on a Filipino table."),
        ing("ing_fish_tilapia", "Fish (Tilapia)", "Tilapia", "Protein", Rarity.COMMON,
            "Fish (Tilapia) (Tilapia) is a protein on a Filipino table."),
        ing("ing_fish_sauce_patis", "Fish Sauce (Patis)", "Patis", "Condiment", Rarity.COMMON,
            "Fish Sauce (Patis) (Patis) is a condiment on a Filipino table."),
        ing("ing_gabi_leaves_taro_leaves_fresh", "Gabi Leaves (Taro Leaves, Fresh)", "Dahon ng Gabi", "Vegetable", Rarity.UNCOMMON,
            "Gabi Leaves (Taro Leaves, Fresh) (Dahon ng Gabi) is a vegetable on a Filipino table."),
        ing("ing_garlic", "Garlic", "Bawang", "Aromatic", Rarity.COMMON,
            "Garlic (Bawang) is a aromatic on a Filipino table."),
        ing("ing_ginger", "Ginger", "Luya", "Aromatic/Spice", Rarity.COMMON,
            "Ginger (Luya) is a aromatic/spice on a Filipino table."),
        ing("ing_goby_frog_river_ingredients", "Goby / Frog (River Ingredients)", "Bulig / Palaka", "Protein", Rarity.UNCOMMON,
            "Goby / Frog (River Ingredients) (Bulig / Palaka) is a protein on a Filipino table."),
        ing("ing_green_mango", "Green Mango", "Manggang Hilaw", "Fruit", Rarity.COMMON,
            "Green Mango (Manggang Hilaw) is a fruit on a Filipino table."),
        ing("ing_green_olives", "Green Olives", "Green Olives", "Condiment/Fruit", Rarity.UNCOMMON,
            "Green Olives (Green Olives) is a condiment/fruit on a Filipino table."),
        ing("ing_green_peas", "Green Peas", "Gisantes", "Vegetable", Rarity.COMMON,
            "Green Peas (Gisantes) is a vegetable on a Filipino table."),
        ing("ing_guava", "Guava", "Bayabas", "Fruit", Rarity.COMMON,
            "Guava (Bayabas) is a fruit on a Filipino table."),
        ing("ing_hotdogs", "Hotdogs", "Hotdog", "Processed Protein", Rarity.COMMON,
            "Hotdogs (Hotdog) is a processed protein on a Filipino table."),
        ing("ing_jackfruit_unripe", "Jackfruit (Unripe)", "Langka (Hilaw)", "Vegetable/Fruit", Rarity.COMMON,
            "Jackfruit (Unripe) (Langka (Hilaw)) is a vegetable/fruit on a Filipino table."),
        ing("ing_jute_leaves_saluyot", "Jute Leaves (Saluyot)", "Saluyot", "Vegetable", Rarity.UNCOMMON,
            "Jute Leaves (Saluyot) (Saluyot) is a vegetable on a Filipino table."),
        ing("ing_kamias", "Kamias", "Kamias / Iba", "Fruit", Rarity.COMMON,
            "Kamias (Kamias / Iba) is a fruit on a Filipino table."),
        ing("ing_knorr_liquid_seasoning", "Knorr Liquid Seasoning", "Knorr Sarap Sauce", "Condiment", Rarity.COMMON,
            "Knorr Liquid Seasoning (Knorr Sarap Sauce) is a condiment on a Filipino table."),
        ing("ing_ladys_choice_mayonnaise", "Lady's Choice Mayonnaise", "Mayo", "Condiment", Rarity.COMMON,
            "Lady's Choice Mayonnaise (Mayo) is a condiment on a Filipino table."),
        ing("ing_lemon", "Lemon", "Lemon", "Fruit", Rarity.COMMON,
            "Lemon (Lemon) is a fruit on a Filipino table."),
        ing("ing_lemongrass", "Lemongrass", "Tanglad", "Herb", Rarity.COMMON,
            "Lemongrass (Tanglad) is a herb on a Filipino table."),
        ing("ing_lime", "Lime", "Dayap", "Fruit", Rarity.COMMON,
            "Lime (Dayap) is a fruit on a Filipino table."),
        ing("ing_liver_spread", "Liver Spread", "Liver Spread", "Processed Protein", Rarity.COMMON,
            "Liver Spread (Liver Spread) is a processed protein on a Filipino table."),
        ing("ing_margarine", "Margarine", "Margarine", "Fat/Dairy Alternative", Rarity.COMMON,
            "Margarine (Margarine) is a fat/dairy alternative on a Filipino table."),
        ing("ing_miki_noodles_fresh", "Miki Noodles (Fresh)", "Miki", "Grain/Noodle", Rarity.COMMON,
            "Miki Noodles (Fresh) (Miki) is a grain/noodle on a Filipino table."),
        ing("ing_milkfish_bangus", "Milkfish (Bangus)", "Bangus", "Protein", Rarity.COMMON,
            "Milkfish (Bangus) (Bangus) is a protein on a Filipino table."),
        ing("ing_muscovado_sugar", "Muscovado Sugar", "Muscovado", "Sweetener", Rarity.COMMON,
            "Muscovado Sugar (Muscovado) is a sweetener on a Filipino table."),
        ing("ing_okra", "Okra", "Okra", "Vegetable", Rarity.COMMON,
            "Okra (Okra) is a vegetable on a Filipino table."),
        ing("ing_onion", "Onion", "Sibuyas", "Aromatic", Rarity.COMMON,
            "Onion (Sibuyas) is a aromatic on a Filipino table."),
        ing("ing_onion_leeks_scallions", "Onion Leeks/Scallions", "Dahon ng Sibuyas", "Herb/Aromatic", Rarity.COMMON,
            "Onion Leeks/Scallions (Dahon ng Sibuyas) is a herb/aromatic on a Filipino table."),
        ing("ing_onion_powder", "Onion Powder", "Onion Powder", "Seasoning", Rarity.COMMON,
            "Onion Powder (Onion Powder) is a seasoning on a Filipino table."),
        ing("ing_oyster_sauce", "Oyster Sauce", "Oyster Sauce", "Condiment", Rarity.COMMON,
            "Oyster Sauce (Oyster Sauce) is a condiment on a Filipino table."),
        ing("ing_palapa_maranao_condiment", "Palapa (Maranao Condiment)", "Palapa", "Condiment", Rarity.RARE,
            "Palapa (Maranao Condiment) (Palapa) is a condiment on a Filipino table."),
        ing("ing_paprika", "Paprika", "Paprika", "Spice", Rarity.COMMON,
            "Paprika (Paprika) is a spice on a Filipino table."),
        ing("ing_peanut_butter", "Peanut Butter", "Peanut Butter", "Condiment", Rarity.COMMON,
            "Peanut Butter (Peanut Butter) is a condiment on a Filipino table."),
        ing("ing_pechay_native", "Pechay (Native)", "Pechay Tagalog", "Vegetable", Rarity.COMMON,
            "Pechay (Native) (Pechay Tagalog) is a vegetable on a Filipino table."),
        ing("ing_pepper_ground_black_white", "Pepper (Ground Black/White)", "Paminta", "Spice", Rarity.COMMON,
            "Pepper (Ground Black/White) (Paminta) is a spice on a Filipino table."),
        ing("ing_peppercorns_whole_black", "Peppercorns (Whole Black)", "Buong Paminta", "Spice", Rarity.COMMON,
            "Peppercorns (Whole Black) (Buong Paminta) is a spice on a Filipino table."),
        ing("ing_pig_blood", "Pig Blood", "Dugo ng Baboy", "Protein/Offal", Rarity.UNCOMMON,
            "Pig Blood (Dugo ng Baboy) is a protein/offal on a Filipino table."),
        ing("ing_pig_face_maskara", "Pig Face (Maskara)", "Maskara", "Protein/Offal", Rarity.UNCOMMON,
            "Pig Face (Maskara) (Maskara) is a protein/offal on a Filipino table."),
        ing("ing_pig_intestines_casing", "Pig Intestines (Casing)", "Bituka ng Baboy", "Protein/Offal", Rarity.UNCOMMON,
            "Pig Intestines (Casing) (Bituka ng Baboy) is a protein/offal on a Filipino table."),
        ing("ing_pig_whole_dressed", "Pig, Whole (Dressed)", "Litson Baboy", "Protein", Rarity.LEGENDARY,
            "Pig, Whole (Dressed) (Litson Baboy) is a protein on a Filipino table."),
        ing("ing_pineapple_juice", "Pineapple Juice", "Katas ng Pinya", "Beverage/Liquid", Rarity.COMMON,
            "Pineapple Juice (Katas ng Pinya) is a beverage/liquid on a Filipino table."),
        ing("ing_pork", "Pork", "Karne ng Baboy", "Protein", Rarity.COMMON,
            "Pork (Karne ng Baboy) is a protein on a Filipino table."),
        ing("ing_pork_belly", "Pork Belly", "Liempo", "Protein", Rarity.COMMON,
            "Pork Belly (Liempo) is a protein on a Filipino table."),
        ing("ing_pork_liver", "Pork Liver", "Atay ng Baboy", "Protein/Offal", Rarity.COMMON,
            "Pork Liver (Atay ng Baboy) is a protein/offal on a Filipino table."),
        ing("ing_pork_offal_mixed", "Pork Offal (Mixed)", "Laman-loob ng Baboy", "Protein/Offal", Rarity.UNCOMMON,
            "Pork Offal (Mixed) (Laman-loob ng Baboy) is a protein/offal on a Filipino table."),
        ing("ing_pork_rind_skin", "Pork Rind/Skin", "Balat ng Baboy", "Protein", Rarity.COMMON,
            "Pork Rind/Skin (Balat ng Baboy) is a protein on a Filipino table."),
        ing("ing_potatoes", "Potatoes", "Patatas", "Vegetable", Rarity.COMMON,
            "Potatoes (Patatas) is a vegetable on a Filipino table."),
        ing("ing_rice_white_cooked", "Rice (White, Cooked)", "Kanin", "Grain", Rarity.COMMON,
            "Rice (White, Cooked) (Kanin) is a grain on a Filipino table."),
        ing("ing_rice_wine_tapuy", "Rice Wine (Tapuy)", "Tapuy", "Beverage", Rarity.RARE,
            "Rice Wine (Tapuy) (Tapuy) is a beverage on a Filipino table."),
        ing("ing_sakurab_shallots_native_shallots", "Sakurab / Shallots (Native Shallots)", "Sakurab", "Aromatic", Rarity.RARE,
            "Sakurab / Shallots (Native Shallots) (Sakurab) is a aromatic on a Filipino table."),
        ing("ing_salt", "Salt", "Asin", "Seasoning", Rarity.COMMON,
            "Salt (Asin) is a seasoning on a Filipino table."),
        ing("ing_santol", "Santol", "Santol", "Fruit", Rarity.COMMON,
            "Santol (Santol) is a fruit on a Filipino table."),
        ing("ing_sesame_seeds", "Sesame Seeds", "Linga", "Spice/Garnish", Rarity.COMMON,
            "Sesame Seeds (Linga) is a spice/garnish on a Filipino table."),
        ing("ing_shallots", "Shallots", "Sibuyas Tagalog", "Aromatic", Rarity.COMMON,
            "Shallots (Sibuyas Tagalog) is a aromatic on a Filipino table."),
        ing("ing_shortening", "Shortening", "Shortening", "Fat", Rarity.COMMON,
            "Shortening (Shortening) is a fat on a Filipino table."),
        ing("ing_shrimp_with_head", "Shrimp (with Head)", "Hipon", "Protein", Rarity.COMMON,
            "Shrimp (with Head) (Hipon) is a protein on a Filipino table."),
        ing("ing_shrimp_paste_bagoong_alamang", "Shrimp Paste (Bagoong Alamang)", "Bagoong Alamang", "Condiment", Rarity.COMMON,
            "Shrimp Paste (Bagoong Alamang) (Bagoong Alamang) is a condiment on a Filipino table."),
        ing("ing_sinigang_mix_powdered", "Sinigang Mix (Powdered)", "Sinigang Mix", "Seasoning", Rarity.COMMON,
            "Sinigang Mix (Powdered) (Sinigang Mix) is a seasoning on a Filipino table."),
        ing("ing_soy_sauce", "Soy Sauce", "Toyo", "Condiment", Rarity.COMMON,
            "Soy Sauce (Toyo) is a condiment on a Filipino table."),
        ing("ing_speck_etag_smoked_pork", "Speck / Etag (Smoked Pork)", "Etag", "Protein", Rarity.RARE,
            "Speck / Etag (Smoked Pork) (Etag) is a protein on a Filipino table."),
        ing("ing_spring_onions", "Spring Onions", "Dahon ng Sibuyas", "Herb/Aromatic", Rarity.COMMON,
            "Spring Onions (Dahon ng Sibuyas) is a herb/aromatic on a Filipino table."),
        ing("ing_string_beans_sitaw", "String Beans (Sitaw)", "Sitaw", "Vegetable", Rarity.COMMON,
            "String Beans (Sitaw) (Sitaw) is a vegetable on a Filipino table."),
        ing("ing_sugar", "Sugar", "Asukal", "Sweetener", Rarity.COMMON,
            "Sugar (Asukal) is a sweetener on a Filipino table."),
        ing("ing_tamarind_young_sampaloc", "Tamarind, Young (Sampaloc)", "Sampalok", "Fruit", Rarity.COMMON,
            "Tamarind, Young (Sampaloc) (Sampalok) is a fruit on a Filipino table."),
        ing("ing_tomato", "Tomato", "Kamatis", "Vegetable/Fruit", Rarity.COMMON,
            "Tomato (Kamatis) is a vegetable/fruit on a Filipino table."),
        ing("ing_tomato_paste", "Tomato Paste", "Tomato Paste", "Condiment", Rarity.COMMON,
            "Tomato Paste (Tomato Paste) is a condiment on a Filipino table."),
        ing("ing_tomato_sauce", "Tomato Sauce", "Tomato Sauce", "Condiment", Rarity.COMMON,
            "Tomato Sauce (Tomato Sauce) is a condiment on a Filipino table."),
        ing("ing_tuna_fresh", "Tuna (Fresh)", "Tulingan/Tuna", "Protein", Rarity.COMMON,
            "Tuna (Fresh) (Tulingan/Tuna) is a protein on a Filipino table."),
        ing("ing_turmeric_powder", "Turmeric (Powder)", "Luyang Dilaw", "Spice", Rarity.COMMON,
            "Turmeric (Powder) (Luyang Dilaw) is a spice on a Filipino table."),
        ing("ing_vegetable_oil", "Vegetable Oil", "Vegetable Oil", "Fat/Oil", Rarity.COMMON,
            "Vegetable Oil (Vegetable Oil) is a fat/oil on a Filipino table."),
        ing("ing_vinegar_white_cane_coconut", "Vinegar (White/Cane/Coconut)", "Suka", "Condiment", Rarity.COMMON,
            "Vinegar (White/Cane/Coconut) (Suka) is a condiment on a Filipino table."),
        ing("ing_water", "Water", "Tubig", "Liquid/Base", Rarity.COMMON,
            "Water (Tubig) is a liquid/base on a Filipino table."),
        ing("ing_water_spinach_kangkong", "Water Spinach (Kangkong)", "Kangkong", "Vegetable", Rarity.COMMON,
            "Water Spinach (Kangkong) (Kangkong) is a vegetable on a Filipino table."),
        ing("ing_white_pepper", "White Pepper", "Puting Paminta", "Spice", Rarity.UNCOMMON,
            "White Pepper (Puting Paminta) is a spice on a Filipino table.")
    )

    val byId: Map<String, Ingredient> = all.associateBy { it.id }

    val total: Int get() = all.size

    fun get(id: String): Ingredient? = byId[id]

    fun ids(): List<String> = all.map { it.id }

    private fun ing(
        id: String,
        name: String,
        localName: String,
        origin: String,
        rarity: Rarity,
        @Suppress("UNUSED_PARAMETER") lore: String
    ) = Ingredient(id, name, localName, origin, tidyLore(name, localName, origin), rarity)

    /** Drop a second “(Bangus)” when the English name already carries it. */
    private fun tidyLore(name: String, localName: String, origin: String): String {
        val who = if (localName.isBlank() || name.contains(localName, ignoreCase = true)) {
            name
        } else {
            "$name ($localName)"
        }
        return "$who is a ${origin.lowercase()} on a Filipino table."
    }
}
