package com.example.kusinakode.ui.learn

import androidx.annotation.DrawableRes
import com.example.kusinakode.R

/**
 * Photography for the ingredients named in the dish dataset.
 * 
 * Generated - do not hand-edit. Keys are the dataset's own ingredient
 * strings, normalised so "White vinegar" and "white vinegar" both resolve.
 * Many strings share one picture (every cut of beef points at the beef
 * photo). Anything with no photograph returns null and the caller falls
 * back to a drawn icon, so an unmatched string is never a crash.
 */
object IngredientArt {

    private val byName: Map<String, Int> = mapOf(
        "all purpose flour" to R.drawable.ing_all_purposeflour,
        "annatto oil" to R.drawable.ing_annatooil,
        "annatto powder" to R.drawable.ing_annatoseeds,
        "annatto seeds" to R.drawable.ing_annatoseeds,
        "annatto atsuete powder" to R.drawable.ing_annatoseeds,
        "bagoong balayan or bagoong monamon anchovy sauce" to R.drawable.ing_bagoong,
        "bamboo skewers" to R.drawable.ing_bambooskewers,
        "banana leaves" to R.drawable.ing_bananaleaves,
        "banana or other suitable leaves for sealing" to R.drawable.ing_bananaleaves,
        "bay leaf" to R.drawable.ing_bayleaves,
        "bay leaves" to R.drawable.ing_bayleaves,
        "beef" to R.drawable.ing_beef,
        "beef bulalo and beef shank" to R.drawable.ing_beef,
        "beef chuck" to R.drawable.ing_beef,
        "beef cube" to R.drawable.ing_beefcubes,
        "beef kenchi kamto" to R.drawable.ing_beef,
        "beef neck bones" to R.drawable.ing_beef,
        "beef powder" to R.drawable.ing_beef,
        "beef ribs" to R.drawable.ing_beef,
        "beef shank" to R.drawable.ing_beef,
        "beef stock" to R.drawable.ing_beefbroth,
        "birds eye chilies" to R.drawable.ing_chilipepper_bird_s_eye,
        "bitter melon" to R.drawable.ing_bittermelon,
        "black pepper" to R.drawable.ing_pepper,
        "black peppercorn" to R.drawable.ing_peppercorns,
        "black peppercorns" to R.drawable.ing_peppercorns,
        "bok choy or shanghai" to R.drawable.ing_bokchoy,
        "brown sugar" to R.drawable.ing_sugar,
        "butter" to R.drawable.ing_butter,
        "cabbage" to R.drawable.ing_cabbage,
        "calamansi" to R.drawable.ing_calamansi,
        "calamansi juice" to R.drawable.ing_calamansi,
        "carrot" to R.drawable.ing_carrots,
        "carrots" to R.drawable.ing_carrots,
        "celery" to R.drawable.ing_celery,
        "chayote" to R.drawable.ing_chayote,
        "cheddar cheese" to R.drawable.ing_cheddarcheese,
        "chicharon" to R.drawable.ing_chicharon,
        "chicken" to R.drawable.ing_chicken,
        "chicken breast or beef" to R.drawable.ing_chicken,
        "chicken broth" to R.drawable.ing_chickenbroth,
        "chicken cubes" to R.drawable.ing_chickenbroth,
        "chicken leg quarter" to R.drawable.ing_chicken,
        "chicken liver" to R.drawable.ing_chickenliver,
        "chicken or native chicken" to R.drawable.ing_chicken,
        "chicken stock" to R.drawable.ing_chickenbroth,
        "chicken pork" to R.drawable.ing_chicken,
        "chili flakes" to R.drawable.ing_chiliflakes,
        "chinese eggplant" to R.drawable.ing_eggplant,
        "cinnamon" to R.drawable.ing_cinnamon,
        "cleaned pig intestines for casing" to R.drawable.ing_pigintestines,
        "coconut cream" to R.drawable.ing_coconutcream,
        "coconut meat mature" to R.drawable.ing_coconutmeat,
        "coconut meat niyog" to R.drawable.ing_coconutmeat,
        "coconut milk" to R.drawable.ing_coconutmilk,
        "cooking oil" to R.drawable.ing_cookingoil,
        "cooking oil or melted butter" to R.drawable.ing_cookingoil,
        "cornstarch" to R.drawable.ing_cornstarch,
        "cucumber" to R.drawable.ing_cucumber,
        "curry powder" to R.drawable.ing_currypowder,
        "daikon radish labanos" to R.drawable.ing_daikonradish,
        "dressed pig" to R.drawable.ing_pig_whole,
        "dried banana blossoms" to R.drawable.ing_bananablossoms,
        "dried bay leaves" to R.drawable.ing_bayleaves,
        "dried shrimp hibe" to R.drawable.ing_hibe,
        "dried taro leaves" to R.drawable.ing_gabileaves,
        "eggplant" to R.drawable.ing_eggplant,
        "finger chilies" to R.drawable.ing_chilipepper_long_green,
        "fish sauce" to R.drawable.ing_fishsauce,
        "fish sauce patis" to R.drawable.ing_fishsauce,
        "flour" to R.drawable.ing_all_purposeflour,
        "fresh bamboo tube" to R.drawable.ing_bambootube,
        "fresh eel iwat kiwat catfish or other available river fish" to R.drawable.ing_eel,
        "fresh miki noodles" to R.drawable.ing_mikinoodles,
        "fresh tuna meat" to R.drawable.ing_tuna,
        "gabi leaves" to R.drawable.ing_gabileaves,
        "garlic" to R.drawable.ing_garlic,
        "garlic cloves" to R.drawable.ing_garlic,
        "ginger" to R.drawable.ing_ginger,
        "ginger sliced" to R.drawable.ing_ginger,
        "green bell peppers" to R.drawable.ing_bellpeppers,
        "green mango" to R.drawable.ing_greenmango,
        "green olives" to R.drawable.ing_greenolives,
        "green peas" to R.drawable.ing_greenpeas,
        "grilled pork belly inihaw na liempo" to R.drawable.ing_porkbelly,
        "ground black pepper" to R.drawable.ing_pepper,
        "guava bayabas" to R.drawable.ing_guava,
        "hot pepper leaves" to R.drawable.ing_pepper,
        "hot red chili pepper" to R.drawable.ing_chilipepper_red_hot,
        "hotdog" to R.drawable.ing_hotdog,
        "hotdogs" to R.drawable.ing_hotdog,
        "indian eggplant" to R.drawable.ing_eggplant,
        "jute leaves" to R.drawable.ing_juteleaves,
        "kamias bilimbi" to R.drawable.ing_kamias,
        "knorr liquid seasoning" to R.drawable.ing_knorrliquidseasoning,
        "labuyo" to R.drawable.ing_chilipepper_bird_s_eye,
        "lady s choice mayonnaise" to R.drawable.ing_lady_schoicemayonnaise,
        "large onions" to R.drawable.ing_onion,
        "lemon" to R.drawable.ing_lemon,
        "lemon or lime soda" to R.drawable.ing_lemon,
        "lemongrass" to R.drawable.ing_lemongrass,
        "lemongrass tanglad" to R.drawable.ing_lemongrass,
        "lime" to R.drawable.ing_lime,
        "liquid seasoning" to R.drawable.ing_knorrliquidseasoning,
        "liver spread" to R.drawable.ing_liverspread,
        "local chili sili" to R.drawable.ing_chilipepper_red_hot,
        "long green chili siling pansigang" to R.drawable.ing_chilipepper_long_green,
        "long green pepper" to R.drawable.ing_chilipepper_long_green,
        "long green pepper siling pansigang" to R.drawable.ing_chilipepper_long_green,
        "margarine" to R.drawable.ing_margarine,
        "milkfish bangus" to R.drawable.ing_milkfish,
        "mixed pork offal such as intestines and pork face" to R.drawable.ing_porkoffal_mixed,
        "muscovado sugar" to R.drawable.ing_muscovadosugar,
        "native pechay or cabbage" to R.drawable.ing_pechay,
        "oil" to R.drawable.ing_cookingoil,
        "okra" to R.drawable.ing_okra,
        "onion" to R.drawable.ing_onion,
        "onion leeks" to R.drawable.ing_onionleeks,
        "onion powder" to R.drawable.ing_onionpowder,
        "onion sliced" to R.drawable.ing_onion,
        "onions" to R.drawable.ing_onion,
        "oyster sauce" to R.drawable.ing_oystersauce,
        "palapa" to R.drawable.ing_palapa,
        "paprika" to R.drawable.ing_paprika,
        "peanut butter" to R.drawable.ing_peanutbutter,
        "pepper" to R.drawable.ing_pepper,
        "pig face maskara" to R.drawable.ing_pigface,
        "pineapple juice" to R.drawable.ing_pineapplejuice,
        "plum tomato" to R.drawable.ing_tomato,
        "plum tomato cubed" to R.drawable.ing_tomato,
        "pork" to R.drawable.ing_pork,
        "pork belly" to R.drawable.ing_porkbelly,
        "pork blood" to R.drawable.ing_pigblood,
        "pork liver" to R.drawable.ing_porkliver,
        "pork rind skin" to R.drawable.ing_porkskin,
        "potato" to R.drawable.ing_potatoes,
        "potatoes" to R.drawable.ing_potatoes,
        "red bell peppers" to R.drawable.ing_bellpeppers,
        "red chili pepper" to R.drawable.ing_chilipepper_red_hot,
        "red onion" to R.drawable.ing_onion,
        "red onions" to R.drawable.ing_onion,
        "rock salt" to R.drawable.ing_salt,
        "salt" to R.drawable.ing_salt,
        "salted black beans" to R.drawable.ing_tausi,
        "santol cotton fruit" to R.drawable.ing_santol,
        "satti sambal chili paste" to R.drawable.ing_sambal,
        "scallions" to R.drawable.ing_springonions,
        "serrano pepper" to R.drawable.ing_chilipepper_long_green,
        "sesame seeds" to R.drawable.ing_sesameseeds,
        "shallots sibuyas tagalog" to R.drawable.ing_shallots,
        "shallots or red onions" to R.drawable.ing_shallots,
        "shortening or butter" to R.drawable.ing_shortening,
        "shrimp paste" to R.drawable.ing_shrimppaste,
        "shrimp paste or salted krill" to R.drawable.ing_shrimppaste,
        "shrimp with head optional" to R.drawable.ing_shrimp,
        "sinigang mix powdered" to R.drawable.ing_sinigangmix,
        "sinigang sa sampaloc mix" to R.drawable.ing_sinigangmix,
        "sirloin beef or carabeef sliced thinly" to R.drawable.ing_beef,
        "sliced unripe jackfruit" to R.drawable.ing_jackfruit,
        "soy sauce" to R.drawable.ing_soysauce,
        "speck etag or any fatty cured smoked pork" to R.drawable.ing_speck,
        "spring onions" to R.drawable.ing_springonions,
        "ssakurab native shallots or shallots" to R.drawable.ing_sakurab,
        "stewing beef" to R.drawable.ing_beef,
        "string beans" to R.drawable.ing_stringbeans,
        "string beans sitaw" to R.drawable.ing_stringbeans,
        "sugar" to R.drawable.ing_sugar,
        "tapuy or any rice wine" to R.drawable.ing_ricewine,
        "thai chili pepper" to R.drawable.ing_chilipepper_bird_s_eye,
        "thai or bird s eye chili" to R.drawable.ing_chilipepper_bird_s_eye,
        "tilapia fried" to R.drawable.ing_tilapia,
        "tomato paste" to R.drawable.ing_tomatopaste,
        "tomato sauce" to R.drawable.ing_tomatosauce,
        "tomato wedged" to R.drawable.ing_tomato,
        "tomatoes" to R.drawable.ing_tomato,
        "turmeric" to R.drawable.ing_turmeric,
        "turmeric powder" to R.drawable.ing_turmeric,
        "vegetable oil" to R.drawable.ing_vegetableoil,
        "vinegar" to R.drawable.ing_vinegar,
        "water" to R.drawable.ing_water,
        "water spinach kangkong" to R.drawable.ing_waterspinach,
        "white onion" to R.drawable.ing_onion,
        "white onions" to R.drawable.ing_onion,
        "white pepper" to R.drawable.ing_whitepepper,
        "white rice cooked" to R.drawable.ing_rice,
        "white sugar" to R.drawable.ing_sugar,
        "white vinegar" to R.drawable.ing_vinegar,
        "whole black peppercorns" to R.drawable.ing_peppercorns,
        "whole chicken" to R.drawable.ing_chicken,
        "whole egg" to R.drawable.ing_egg,
        "whole peppercorn" to R.drawable.ing_peppercorns,
        "whole peppercorns" to R.drawable.ing_peppercorns,
        "yellow onion" to R.drawable.ing_onion,
        "young coconut meat" to R.drawable.ing_coconutmeat,
        "young coconut water" to R.drawable.ing_coconutwater,
        "young tamarind sampaloc" to R.drawable.ing_tamarind_young,
        "vinegar cane white or coconut vinegar" to R.drawable.ing_vinegar,
    )

    /** Drawable for [name], or null when we have no picture for it. */
    @DrawableRes
    fun forName(name: String): Int? =
        byName[name.lowercase().replace(Regex("[^a-z0-9]+"), " ").trim()]
}
